
# This file is automatically generated, you probably don't want to edit this

boxBehnkenOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "boxBehnkenOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            numberFactors = NULL,
            nameFactors = NULL,
            defaultLevels = NULL,
            numberCenter = NULL,
            randomize = NULL,
            seed = 3432, ...) {

            super$initialize(
                package="DoE",
                name="boxBehnken",
                requiresData=TRUE,
                ...)

            private$..numberFactors <- jmvcore::OptionInteger$new(
                "numberFactors",
                numberFactors)
            private$..nameFactors <- jmvcore::OptionString$new(
                "nameFactors",
                nameFactors)
            private$..defaultLevels <- jmvcore::OptionString$new(
                "defaultLevels",
                defaultLevels)
            private$..numberCenter <- jmvcore::OptionInteger$new(
                "numberCenter",
                numberCenter)
            private$..randomize <- jmvcore::OptionBool$new(
                "randomize",
                randomize)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=3432)

            self$.addOption(private$..numberFactors)
            self$.addOption(private$..nameFactors)
            self$.addOption(private$..defaultLevels)
            self$.addOption(private$..numberCenter)
            self$.addOption(private$..randomize)
            self$.addOption(private$..seed)
        }),
    active = list(
        numberFactors = function() private$..numberFactors$value,
        nameFactors = function() private$..nameFactors$value,
        defaultLevels = function() private$..defaultLevels$value,
        numberCenter = function() private$..numberCenter$value,
        randomize = function() private$..randomize$value,
        seed = function() private$..seed$value),
    private = list(
        ..numberFactors = NA,
        ..nameFactors = NA,
        ..defaultLevels = NA,
        ..numberCenter = NA,
        ..randomize = NA,
        ..seed = NA)
)

boxBehnkenResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "boxBehnkenResults",
    inherit = jmvcore::Group,
    active = list(
        usage = function() private$.items[["usage"]],
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Box Behnken")
            self$add(jmvcore::Html$new(
                options=options,
                name="usage",
                title="Usage",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Box Behnken"))}))

boxBehnkenBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "boxBehnkenBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "DoE",
                name = "boxBehnken",
                version = c(1,0,0),
                options = options,
                results = boxBehnkenResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Box Behnken
#'
#' 
#' @param data .
#' @param numberFactors .
#' @param nameFactors .
#' @param defaultLevels .
#' @param numberCenter .
#' @param randomize .
#' @param seed .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$usage} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
boxBehnken <- function(
    data,
    numberFactors,
    nameFactors,
    defaultLevels,
    numberCenter,
    randomize,
    seed = 3432) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("boxBehnken requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- boxBehnkenOptions$new(
        numberFactors = numberFactors,
        nameFactors = nameFactors,
        defaultLevels = defaultLevels,
        numberCenter = numberCenter,
        randomize = randomize,
        seed = seed)

    analysis <- boxBehnkenClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

