
# This file is automatically generated, you probably don't want to edit this

centralCompOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "centralCompOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            numberCenter = NULL,
            numberCube = NULL,
            alpha = "rotatable",
            numberFactors = NULL,
            nameFactors = NULL,
            defaultLevels = NULL,
            numberBlocks = 1,
            nameBlocks = "Blocks",
            replications = 1,
            randomize = NULL,
            seed1 = 2784,
            seed2 = 8926, ...) {

            super$initialize(
                package="DoE",
                name="centralComp",
                requiresData=TRUE,
                ...)

            private$..numberCenter <- jmvcore::OptionInteger$new(
                "numberCenter",
                numberCenter)
            private$..numberCube <- jmvcore::OptionInteger$new(
                "numberCube",
                numberCube)
            private$..alpha <- jmvcore::OptionList$new(
                "alpha",
                alpha,
                options=list(
                    "orthogonal",
                    "rotatable",
                    "1"),
                default="rotatable")
            private$..numberFactors <- jmvcore::OptionInteger$new(
                "numberFactors",
                numberFactors)
            private$..nameFactors <- jmvcore::OptionString$new(
                "nameFactors",
                nameFactors)
            private$..defaultLevels <- jmvcore::OptionString$new(
                "defaultLevels",
                defaultLevels)
            private$..numberBlocks <- jmvcore::OptionInteger$new(
                "numberBlocks",
                numberBlocks,
                default=1)
            private$..nameBlocks <- jmvcore::OptionString$new(
                "nameBlocks",
                nameBlocks,
                default="Blocks")
            private$..replications <- jmvcore::OptionInteger$new(
                "replications",
                replications,
                default=1)
            private$..randomize <- jmvcore::OptionBool$new(
                "randomize",
                randomize)
            private$..seed1 <- jmvcore::OptionInteger$new(
                "seed1",
                seed1,
                default=2784)
            private$..seed2 <- jmvcore::OptionInteger$new(
                "seed2",
                seed2,
                default=8926)

            self$.addOption(private$..numberCenter)
            self$.addOption(private$..numberCube)
            self$.addOption(private$..alpha)
            self$.addOption(private$..numberFactors)
            self$.addOption(private$..nameFactors)
            self$.addOption(private$..defaultLevels)
            self$.addOption(private$..numberBlocks)
            self$.addOption(private$..nameBlocks)
            self$.addOption(private$..replications)
            self$.addOption(private$..randomize)
            self$.addOption(private$..seed1)
            self$.addOption(private$..seed2)
        }),
    active = list(
        numberCenter = function() private$..numberCenter$value,
        numberCube = function() private$..numberCube$value,
        alpha = function() private$..alpha$value,
        numberFactors = function() private$..numberFactors$value,
        nameFactors = function() private$..nameFactors$value,
        defaultLevels = function() private$..defaultLevels$value,
        numberBlocks = function() private$..numberBlocks$value,
        nameBlocks = function() private$..nameBlocks$value,
        replications = function() private$..replications$value,
        randomize = function() private$..randomize$value,
        seed1 = function() private$..seed1$value,
        seed2 = function() private$..seed2$value),
    private = list(
        ..numberCenter = NA,
        ..numberCube = NA,
        ..alpha = NA,
        ..numberFactors = NA,
        ..nameFactors = NA,
        ..defaultLevels = NA,
        ..numberBlocks = NA,
        ..nameBlocks = NA,
        ..replications = NA,
        ..randomize = NA,
        ..seed1 = NA,
        ..seed2 = NA)
)

centralCompResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "centralCompResults",
    inherit = jmvcore::Group,
    active = list(
        usage = function() private$.items[["usage"]],
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Central Composite")
            self$add(jmvcore::Html$new(
                options=options,
                name="usage",
                title="Usage",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Central Composite"))}))

centralCompBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "centralCompBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "DoE",
                name = "centralComp",
                version = c(1,0,0),
                options = options,
                results = centralCompResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Central Composite
#'
#' 
#' @param data .
#' @param numberCenter .
#' @param numberCube .
#' @param alpha .
#' @param numberFactors .
#' @param nameFactors .
#' @param defaultLevels .
#' @param numberBlocks .
#' @param nameBlocks .
#' @param replications .
#' @param randomize .
#' @param seed1 .
#' @param seed2 .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$usage} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
centralComp <- function(
    data,
    numberCenter,
    numberCube,
    alpha = "rotatable",
    numberFactors,
    nameFactors,
    defaultLevels,
    numberBlocks = 1,
    nameBlocks = "Blocks",
    replications = 1,
    randomize,
    seed1 = 2784,
    seed2 = 8926) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("centralComp requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- centralCompOptions$new(
        numberCenter = numberCenter,
        numberCube = numberCube,
        alpha = alpha,
        numberFactors = numberFactors,
        nameFactors = nameFactors,
        defaultLevels = defaultLevels,
        numberBlocks = numberBlocks,
        nameBlocks = nameBlocks,
        replications = replications,
        randomize = randomize,
        seed1 = seed1,
        seed2 = seed2)

    analysis <- centralCompClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

