
# This file is automatically generated, you probably don't want to edit this

extremeVerticesOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "extremeVerticesOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            numberFactors = NULL,
            lowerConstraints = NULL,
            upperConstraints = NULL, ...) {

            super$initialize(
                package="DoE",
                name="extremeVertices",
                requiresData=TRUE,
                ...)

            private$..numberFactors <- jmvcore::OptionInteger$new(
                "numberFactors",
                numberFactors)
            private$..lowerConstraints <- jmvcore::OptionString$new(
                "lowerConstraints",
                lowerConstraints)
            private$..upperConstraints <- jmvcore::OptionString$new(
                "upperConstraints",
                upperConstraints)

            self$.addOption(private$..numberFactors)
            self$.addOption(private$..lowerConstraints)
            self$.addOption(private$..upperConstraints)
        }),
    active = list(
        numberFactors = function() private$..numberFactors$value,
        lowerConstraints = function() private$..lowerConstraints$value,
        upperConstraints = function() private$..upperConstraints$value),
    private = list(
        ..numberFactors = NA,
        ..lowerConstraints = NA,
        ..upperConstraints = NA)
)

extremeVerticesResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "extremeVerticesResults",
    inherit = jmvcore::Group,
    active = list(
        usage = function() private$.items[["usage"]],
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Extreme Vertices")
            self$add(jmvcore::Html$new(
                options=options,
                name="usage",
                title="Usage",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Extreme Vertices"))}))

extremeVerticesBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "extremeVerticesBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "DoE",
                name = "extremeVertices",
                version = c(1,0,0),
                options = options,
                results = extremeVerticesResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Extreme Vertices
#'
#' 
#' @param data .
#' @param numberFactors .
#' @param lowerConstraints .
#' @param upperConstraints .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$usage} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
extremeVertices <- function(
    data,
    numberFactors,
    lowerConstraints,
    upperConstraints) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("extremeVertices requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- extremeVerticesOptions$new(
        numberFactors = numberFactors,
        lowerConstraints = lowerConstraints,
        upperConstraints = upperConstraints)

    analysis <- extremeVerticesClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

