
# This file is automatically generated, you probably don't want to edit this

fracFacOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "fracFacOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            numberRuns = NULL,
            numberFactors = NULL,
            nameFactors = NULL,
            defaultLevels = NULL,
            numberCenter = 0,
            numberBlocks = 1,
            nameBlocks = "Blocks",
            aliased2fis = NULL,
            aliasInfo = "2",
            replications = 1,
            repeatOnly = NULL,
            seed = 8195,
            randomize = NULL,
            resolution = NULL, ...) {

            super$initialize(
                package="DoE",
                name="fracFac",
                requiresData=TRUE,
                ...)

            private$..numberRuns <- jmvcore::OptionInteger$new(
                "numberRuns",
                numberRuns)
            private$..numberFactors <- jmvcore::OptionInteger$new(
                "numberFactors",
                numberFactors)
            private$..nameFactors <- jmvcore::OptionString$new(
                "nameFactors",
                nameFactors)
            private$..defaultLevels <- jmvcore::OptionString$new(
                "defaultLevels",
                defaultLevels)
            private$..numberCenter <- jmvcore::OptionInteger$new(
                "numberCenter",
                numberCenter,
                default=0)
            private$..numberBlocks <- jmvcore::OptionInteger$new(
                "numberBlocks",
                numberBlocks,
                default=1)
            private$..nameBlocks <- jmvcore::OptionString$new(
                "nameBlocks",
                nameBlocks,
                default="Blocks")
            private$..aliased2fis <- jmvcore::OptionBool$new(
                "aliased2fis",
                aliased2fis)
            private$..aliasInfo <- jmvcore::OptionList$new(
                "aliasInfo",
                aliasInfo,
                options=list(
                    "2",
                    "3"),
                default="2")
            private$..replications <- jmvcore::OptionInteger$new(
                "replications",
                replications,
                default=1)
            private$..repeatOnly <- jmvcore::OptionBool$new(
                "repeatOnly",
                repeatOnly)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=8195)
            private$..randomize <- jmvcore::OptionBool$new(
                "randomize",
                randomize)
            private$..resolution <- jmvcore::OptionList$new(
                "resolution",
                resolution,
                options=list(
                    "3",
                    "4",
                    "5"))

            self$.addOption(private$..numberRuns)
            self$.addOption(private$..numberFactors)
            self$.addOption(private$..nameFactors)
            self$.addOption(private$..defaultLevels)
            self$.addOption(private$..numberCenter)
            self$.addOption(private$..numberBlocks)
            self$.addOption(private$..nameBlocks)
            self$.addOption(private$..aliased2fis)
            self$.addOption(private$..aliasInfo)
            self$.addOption(private$..replications)
            self$.addOption(private$..repeatOnly)
            self$.addOption(private$..seed)
            self$.addOption(private$..randomize)
            self$.addOption(private$..resolution)
        }),
    active = list(
        numberRuns = function() private$..numberRuns$value,
        numberFactors = function() private$..numberFactors$value,
        nameFactors = function() private$..nameFactors$value,
        defaultLevels = function() private$..defaultLevels$value,
        numberCenter = function() private$..numberCenter$value,
        numberBlocks = function() private$..numberBlocks$value,
        nameBlocks = function() private$..nameBlocks$value,
        aliased2fis = function() private$..aliased2fis$value,
        aliasInfo = function() private$..aliasInfo$value,
        replications = function() private$..replications$value,
        repeatOnly = function() private$..repeatOnly$value,
        seed = function() private$..seed$value,
        randomize = function() private$..randomize$value,
        resolution = function() private$..resolution$value),
    private = list(
        ..numberRuns = NA,
        ..numberFactors = NA,
        ..nameFactors = NA,
        ..defaultLevels = NA,
        ..numberCenter = NA,
        ..numberBlocks = NA,
        ..nameBlocks = NA,
        ..aliased2fis = NA,
        ..aliasInfo = NA,
        ..replications = NA,
        ..repeatOnly = NA,
        ..seed = NA,
        ..randomize = NA,
        ..resolution = NA)
)

fracFacResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "fracFacResults",
    inherit = jmvcore::Group,
    active = list(
        usage = function() private$.items[["usage"]],
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Fractional Factorial")
            self$add(jmvcore::Html$new(
                options=options,
                name="usage",
                title="Usage",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Fractional Factorial"))}))

fracFacBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "fracFacBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "DoE",
                name = "fracFac",
                version = c(1,0,0),
                options = options,
                results = fracFacResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Fractional Factorial
#'
#' 
#' @param data .
#' @param numberRuns .
#' @param numberFactors .
#' @param nameFactors .
#' @param defaultLevels .
#' @param numberCenter .
#' @param numberBlocks .
#' @param nameBlocks .
#' @param aliased2fis .
#' @param aliasInfo .
#' @param replications .
#' @param repeatOnly .
#' @param seed .
#' @param randomize .
#' @param resolution .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$usage} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
fracFac <- function(
    data,
    numberRuns,
    numberFactors,
    nameFactors,
    defaultLevels,
    numberCenter = 0,
    numberBlocks = 1,
    nameBlocks = "Blocks",
    aliased2fis,
    aliasInfo = "2",
    replications = 1,
    repeatOnly,
    seed = 8195,
    randomize,
    resolution) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("fracFac requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- fracFacOptions$new(
        numberRuns = numberRuns,
        numberFactors = numberFactors,
        nameFactors = nameFactors,
        defaultLevels = defaultLevels,
        numberCenter = numberCenter,
        numberBlocks = numberBlocks,
        nameBlocks = nameBlocks,
        aliased2fis = aliased2fis,
        aliasInfo = aliasInfo,
        replications = replications,
        repeatOnly = repeatOnly,
        seed = seed,
        randomize = randomize,
        resolution = resolution)

    analysis <- fracFacClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

