
# This file is automatically generated, you probably don't want to edit this

fullFacOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "fullFacOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            numberFactors = NULL,
            nameFactors = NULL,
            numberFactorLevels = NULL,
            eachFactorLevels = NULL,
            numberBlocks = 1,
            nameBlocks = "Blocks",
            replications = 1,
            repeatOnly = NULL,
            seed = 25474,
            randomize = NULL, ...) {

            super$initialize(
                package="DoE",
                name="fullFac",
                requiresData=TRUE,
                ...)

            private$..numberFactors <- jmvcore::OptionInteger$new(
                "numberFactors",
                numberFactors)
            private$..nameFactors <- jmvcore::OptionString$new(
                "nameFactors",
                nameFactors)
            private$..numberFactorLevels <- jmvcore::OptionString$new(
                "numberFactorLevels",
                numberFactorLevels)
            private$..eachFactorLevels <- jmvcore::OptionString$new(
                "eachFactorLevels",
                eachFactorLevels)
            private$..numberBlocks <- jmvcore::OptionInteger$new(
                "numberBlocks",
                numberBlocks,
                default=1)
            private$..nameBlocks <- jmvcore::OptionString$new(
                "nameBlocks",
                nameBlocks,
                default="Blocks")
            private$..replications <- jmvcore::OptionInteger$new(
                "replications",
                replications,
                default=1)
            private$..repeatOnly <- jmvcore::OptionBool$new(
                "repeatOnly",
                repeatOnly)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=25474)
            private$..randomize <- jmvcore::OptionBool$new(
                "randomize",
                randomize)

            self$.addOption(private$..numberFactors)
            self$.addOption(private$..nameFactors)
            self$.addOption(private$..numberFactorLevels)
            self$.addOption(private$..eachFactorLevels)
            self$.addOption(private$..numberBlocks)
            self$.addOption(private$..nameBlocks)
            self$.addOption(private$..replications)
            self$.addOption(private$..repeatOnly)
            self$.addOption(private$..seed)
            self$.addOption(private$..randomize)
        }),
    active = list(
        numberFactors = function() private$..numberFactors$value,
        nameFactors = function() private$..nameFactors$value,
        numberFactorLevels = function() private$..numberFactorLevels$value,
        eachFactorLevels = function() private$..eachFactorLevels$value,
        numberBlocks = function() private$..numberBlocks$value,
        nameBlocks = function() private$..nameBlocks$value,
        replications = function() private$..replications$value,
        repeatOnly = function() private$..repeatOnly$value,
        seed = function() private$..seed$value,
        randomize = function() private$..randomize$value),
    private = list(
        ..numberFactors = NA,
        ..nameFactors = NA,
        ..numberFactorLevels = NA,
        ..eachFactorLevels = NA,
        ..numberBlocks = NA,
        ..nameBlocks = NA,
        ..replications = NA,
        ..repeatOnly = NA,
        ..seed = NA,
        ..randomize = NA)
)

fullFacResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "fullFacResults",
    inherit = jmvcore::Group,
    active = list(
        usage = function() private$.items[["usage"]],
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Full Factorial")
            self$add(jmvcore::Html$new(
                options=options,
                name="usage",
                title="Usage",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Full Factorial"))}))

fullFacBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "fullFacBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "DoE",
                name = "fullFac",
                version = c(1,0,0),
                options = options,
                results = fullFacResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Full Factorial
#'
#' 
#' @param data .
#' @param numberFactors .
#' @param nameFactors .
#' @param numberFactorLevels .
#' @param eachFactorLevels .
#' @param numberBlocks .
#' @param nameBlocks .
#' @param replications .
#' @param repeatOnly .
#' @param seed .
#' @param randomize .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$usage} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
fullFac <- function(
    data,
    numberFactors,
    nameFactors,
    numberFactorLevels,
    eachFactorLevels,
    numberBlocks = 1,
    nameBlocks = "Blocks",
    replications = 1,
    repeatOnly,
    seed = 25474,
    randomize) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("fullFac requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- fullFacOptions$new(
        numberFactors = numberFactors,
        nameFactors = nameFactors,
        numberFactorLevels = numberFactorLevels,
        eachFactorLevels = eachFactorLevels,
        numberBlocks = numberBlocks,
        nameBlocks = nameBlocks,
        replications = replications,
        repeatOnly = repeatOnly,
        seed = seed,
        randomize = randomize)

    analysis <- fullFacClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

