
# This file is automatically generated, you probably don't want to edit this

linModelOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "linModelOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            indep = NULL,
            deps = NULL,
            linRegSwitch = FALSE,
            formula = NULL,
            anovaSwitch = FALSE,
            anovaType = "2",
            paretoSwitch = FALSE,
            normalSwitch = FALSE,
            isHalfNormal = TRUE,
            alpha = NULL,
            mainEffectsSwitch = FALSE,
            interactionSwitch = FALSE,
            contourFormula = NULL,
            contourSwitch = FALSE, ...) {

            super$initialize(
                package="DoE",
                name="linModel",
                requiresData=TRUE,
                ...)

            private$..indep <- jmvcore::OptionVariable$new(
                "indep",
                indep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..deps <- jmvcore::OptionVariables$new(
                "deps",
                deps)
            private$..linRegSwitch <- jmvcore::OptionBool$new(
                "linRegSwitch",
                linRegSwitch,
                default=FALSE)
            private$..formula <- jmvcore::OptionString$new(
                "formula",
                formula)
            private$..anovaSwitch <- jmvcore::OptionBool$new(
                "anovaSwitch",
                anovaSwitch,
                default=FALSE)
            private$..anovaType <- jmvcore::OptionList$new(
                "anovaType",
                anovaType,
                options=list(
                    "2",
                    "3"),
                default="2")
            private$..paretoSwitch <- jmvcore::OptionBool$new(
                "paretoSwitch",
                paretoSwitch,
                default=FALSE)
            private$..normalSwitch <- jmvcore::OptionBool$new(
                "normalSwitch",
                normalSwitch,
                default=FALSE)
            private$..isHalfNormal <- jmvcore::OptionBool$new(
                "isHalfNormal",
                isHalfNormal,
                default=TRUE)
            private$..alpha <- jmvcore::OptionString$new(
                "alpha",
                alpha)
            private$..mainEffectsSwitch <- jmvcore::OptionBool$new(
                "mainEffectsSwitch",
                mainEffectsSwitch,
                default=FALSE)
            private$..interactionSwitch <- jmvcore::OptionBool$new(
                "interactionSwitch",
                interactionSwitch,
                default=FALSE)
            private$..contourFormula <- jmvcore::OptionString$new(
                "contourFormula",
                contourFormula)
            private$..contourSwitch <- jmvcore::OptionBool$new(
                "contourSwitch",
                contourSwitch,
                default=FALSE)

            self$.addOption(private$..indep)
            self$.addOption(private$..deps)
            self$.addOption(private$..linRegSwitch)
            self$.addOption(private$..formula)
            self$.addOption(private$..anovaSwitch)
            self$.addOption(private$..anovaType)
            self$.addOption(private$..paretoSwitch)
            self$.addOption(private$..normalSwitch)
            self$.addOption(private$..isHalfNormal)
            self$.addOption(private$..alpha)
            self$.addOption(private$..mainEffectsSwitch)
            self$.addOption(private$..interactionSwitch)
            self$.addOption(private$..contourFormula)
            self$.addOption(private$..contourSwitch)
        }),
    active = list(
        indep = function() private$..indep$value,
        deps = function() private$..deps$value,
        linRegSwitch = function() private$..linRegSwitch$value,
        formula = function() private$..formula$value,
        anovaSwitch = function() private$..anovaSwitch$value,
        anovaType = function() private$..anovaType$value,
        paretoSwitch = function() private$..paretoSwitch$value,
        normalSwitch = function() private$..normalSwitch$value,
        isHalfNormal = function() private$..isHalfNormal$value,
        alpha = function() private$..alpha$value,
        mainEffectsSwitch = function() private$..mainEffectsSwitch$value,
        interactionSwitch = function() private$..interactionSwitch$value,
        contourFormula = function() private$..contourFormula$value,
        contourSwitch = function() private$..contourSwitch$value),
    private = list(
        ..indep = NA,
        ..deps = NA,
        ..linRegSwitch = NA,
        ..formula = NA,
        ..anovaSwitch = NA,
        ..anovaType = NA,
        ..paretoSwitch = NA,
        ..normalSwitch = NA,
        ..isHalfNormal = NA,
        ..alpha = NA,
        ..mainEffectsSwitch = NA,
        ..interactionSwitch = NA,
        ..contourFormula = NA,
        ..contourSwitch = NA)
)

linModelResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "linModelResults",
    inherit = jmvcore::Group,
    active = list(
        usage = function() private$.items[["usage"]],
        linearReg = function() private$.items[["linearReg"]],
        anova = function() private$.items[["anova"]],
        paretoPlot = function() private$.items[["paretoPlot"]],
        normalPlot = function() private$.items[["normalPlot"]],
        mainEffectsPlot = function() private$.items[["mainEffectsPlot"]],
        interactionPlot = function() private$.items[["interactionPlot"]],
        contourPlot = function() private$.items[["contourPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Linear Model")
            self$add(jmvcore::Html$new(
                options=options,
                name="usage",
                title="Usage",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="linearReg",
                title="Linear Regression"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="anova",
                title="ANOVA"))
            self$add(jmvcore::Image$new(
                options=options,
                name="paretoPlot",
                title="Pareto Plot",
                width=350,
                height=350,
                renderFun=".paretoPlot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="normalPlot",
                title="Normal Plot",
                width=350,
                height=350,
                renderFun=".normalPlot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="mainEffectsPlot",
                title="Main Effects Plot",
                width=350,
                height=350,
                renderFun=".mainEffectsPlot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="interactionPlot",
                title="Interaction Plot",
                width=350,
                height=350,
                renderFun=".interactionPlot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="contourPlot",
                title="Contour Plot",
                width=350,
                height=350,
                renderFun=".contourPlot"))}))

linModelBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "linModelBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "DoE",
                name = "linModel",
                version = c(1,0,0),
                options = options,
                results = linModelResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Linear Model
#'
#' 
#' @param data .
#' @param indep .
#' @param deps .
#' @param linRegSwitch .
#' @param formula .
#' @param anovaSwitch .
#' @param anovaType .
#' @param paretoSwitch .
#' @param normalSwitch .
#' @param isHalfNormal .
#' @param alpha .
#' @param mainEffectsSwitch .
#' @param interactionSwitch .
#' @param contourFormula .
#' @param contourSwitch .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$usage} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$linearReg} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$anova} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$paretoPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$normalPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$mainEffectsPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$interactionPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$contourPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
linModel <- function(
    data,
    indep,
    deps,
    linRegSwitch = FALSE,
    formula,
    anovaSwitch = FALSE,
    anovaType = "2",
    paretoSwitch = FALSE,
    normalSwitch = FALSE,
    isHalfNormal = TRUE,
    alpha,
    mainEffectsSwitch = FALSE,
    interactionSwitch = FALSE,
    contourFormula,
    contourSwitch = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("linModel requires jmvcore to be installed (restart may be required)")

    if ( ! missing(indep)) indep <- jmvcore::resolveQuo(jmvcore::enquo(indep))
    if ( ! missing(deps)) deps <- jmvcore::resolveQuo(jmvcore::enquo(deps))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(indep), indep, NULL),
            `if`( ! missing(deps), deps, NULL))


    options <- linModelOptions$new(
        indep = indep,
        deps = deps,
        linRegSwitch = linRegSwitch,
        formula = formula,
        anovaSwitch = anovaSwitch,
        anovaType = anovaType,
        paretoSwitch = paretoSwitch,
        normalSwitch = normalSwitch,
        isHalfNormal = isHalfNormal,
        alpha = alpha,
        mainEffectsSwitch = mainEffectsSwitch,
        interactionSwitch = interactionSwitch,
        contourFormula = contourFormula,
        contourSwitch = contourSwitch)

    analysis <- linModelClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

