
# This file is automatically generated, you probably don't want to edit this

linModelOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "linModelOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            indep = NULL,
            deps = NULL,
            formula = NULL,
            anovaSwitch = FALSE,
            anovaType = "2",
            norVar = NULL,
            mainEffectsFormula = NULL,
            interactionFactorX = NULL,
            interactionTraceFactor = NULL,
            interactionFactorY = NULL,
            paretoSwitch = FALSE,
            contourFormula = NULL, ...) {

            super$initialize(
                package="DoE",
                name="linModel",
                requiresData=TRUE,
                ...)

            private$..indep <- jmvcore::OptionVariable$new(
                "indep",
                indep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..deps <- jmvcore::OptionVariables$new(
                "deps",
                deps)
            private$..formula <- jmvcore::OptionString$new(
                "formula",
                formula)
            private$..anovaSwitch <- jmvcore::OptionBool$new(
                "anovaSwitch",
                anovaSwitch,
                default=FALSE)
            private$..anovaType <- jmvcore::OptionList$new(
                "anovaType",
                anovaType,
                options=list(
                    "2",
                    "3"),
                default="2")
            private$..norVar <- jmvcore::OptionString$new(
                "norVar",
                norVar)
            private$..mainEffectsFormula <- jmvcore::OptionString$new(
                "mainEffectsFormula",
                mainEffectsFormula)
            private$..interactionFactorX <- jmvcore::OptionString$new(
                "interactionFactorX",
                interactionFactorX)
            private$..interactionTraceFactor <- jmvcore::OptionString$new(
                "interactionTraceFactor",
                interactionTraceFactor)
            private$..interactionFactorY <- jmvcore::OptionString$new(
                "interactionFactorY",
                interactionFactorY)
            private$..paretoSwitch <- jmvcore::OptionBool$new(
                "paretoSwitch",
                paretoSwitch,
                default=FALSE)
            private$..contourFormula <- jmvcore::OptionString$new(
                "contourFormula",
                contourFormula)

            self$.addOption(private$..indep)
            self$.addOption(private$..deps)
            self$.addOption(private$..formula)
            self$.addOption(private$..anovaSwitch)
            self$.addOption(private$..anovaType)
            self$.addOption(private$..norVar)
            self$.addOption(private$..mainEffectsFormula)
            self$.addOption(private$..interactionFactorX)
            self$.addOption(private$..interactionTraceFactor)
            self$.addOption(private$..interactionFactorY)
            self$.addOption(private$..paretoSwitch)
            self$.addOption(private$..contourFormula)
        }),
    active = list(
        indep = function() private$..indep$value,
        deps = function() private$..deps$value,
        formula = function() private$..formula$value,
        anovaSwitch = function() private$..anovaSwitch$value,
        anovaType = function() private$..anovaType$value,
        norVar = function() private$..norVar$value,
        mainEffectsFormula = function() private$..mainEffectsFormula$value,
        interactionFactorX = function() private$..interactionFactorX$value,
        interactionTraceFactor = function() private$..interactionTraceFactor$value,
        interactionFactorY = function() private$..interactionFactorY$value,
        paretoSwitch = function() private$..paretoSwitch$value,
        contourFormula = function() private$..contourFormula$value),
    private = list(
        ..indep = NA,
        ..deps = NA,
        ..formula = NA,
        ..anovaSwitch = NA,
        ..anovaType = NA,
        ..norVar = NA,
        ..mainEffectsFormula = NA,
        ..interactionFactorX = NA,
        ..interactionTraceFactor = NA,
        ..interactionFactorY = NA,
        ..paretoSwitch = NA,
        ..contourFormula = NA)
)

linModelResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "linModelResults",
    inherit = jmvcore::Group,
    active = list(
        usage = function() private$.items[["usage"]],
        linearReg = function() private$.items[["linearReg"]],
        anova = function() private$.items[["anova"]],
        normalPlot = function() private$.items[["normalPlot"]],
        mainEffectsPlot = function() private$.items[["mainEffectsPlot"]],
        interactionPlot = function() private$.items[["interactionPlot"]],
        paretoPlot = function() private$.items[["paretoPlot"]],
        contourPlot = function() private$.items[["contourPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Linear Model")
            self$add(jmvcore::Html$new(
                options=options,
                name="usage",
                title="Usage",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="linearReg",
                title="Linear Regression"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="anova",
                title="ANOVA"))
            self$add(jmvcore::Image$new(
                options=options,
                name="normalPlot",
                title="Normal Plot",
                width=450,
                height=350,
                renderFun=".normalPlot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="mainEffectsPlot",
                title="Main Effects Plot",
                width=450,
                height=350,
                renderFun=".mainEffectsPlot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="interactionPlot",
                title="Interaction Plot",
                width=450,
                height=350,
                renderFun=".interactionPlot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="paretoPlot",
                title="Pareto Plot",
                width=450,
                height=350,
                renderFun=".paretoPlot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="contourPlot",
                title="Contour Plot",
                width=450,
                height=350,
                renderFun=".contourPlot"))}))

linModelBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "linModelBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "DoE",
                name = "linModel",
                version = c(1,0,0),
                options = options,
                results = linModelResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Linear Model
#'
#' 
#' @param data .
#' @param indep .
#' @param deps .
#' @param formula .
#' @param anovaSwitch .
#' @param anovaType .
#' @param norVar .
#' @param mainEffectsFormula .
#' @param interactionFactorX .
#' @param interactionTraceFactor .
#' @param interactionFactorY .
#' @param paretoSwitch .
#' @param contourFormula .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$usage} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$linearReg} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$anova} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$normalPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$mainEffectsPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$interactionPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$paretoPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$contourPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
linModel <- function(
    data,
    indep,
    deps,
    formula,
    anovaSwitch = FALSE,
    anovaType = "2",
    norVar,
    mainEffectsFormula,
    interactionFactorX,
    interactionTraceFactor,
    interactionFactorY,
    paretoSwitch = FALSE,
    contourFormula) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("linModel requires jmvcore to be installed (restart may be required)")

    if ( ! missing(indep)) indep <- jmvcore::resolveQuo(jmvcore::enquo(indep))
    if ( ! missing(deps)) deps <- jmvcore::resolveQuo(jmvcore::enquo(deps))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(indep), indep, NULL),
            `if`( ! missing(deps), deps, NULL))


    options <- linModelOptions$new(
        indep = indep,
        deps = deps,
        formula = formula,
        anovaSwitch = anovaSwitch,
        anovaType = anovaType,
        norVar = norVar,
        mainEffectsFormula = mainEffectsFormula,
        interactionFactorX = interactionFactorX,
        interactionTraceFactor = interactionTraceFactor,
        interactionFactorY = interactionFactorY,
        paretoSwitch = paretoSwitch,
        contourFormula = contourFormula)

    analysis <- linModelClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

