
# This file is automatically generated, you probably don't want to edit this

mainEffectsInteractionOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mainEffectsInteractionOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            mainEffectsFormula = NULL,
            interactionFactorX = NULL,
            interactionTraceFactor = NULL,
            interactionFactorY = NULL, ...) {

            super$initialize(
                package="DoE",
                name="mainEffectsInteraction",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars)
            private$..mainEffectsFormula <- jmvcore::OptionString$new(
                "mainEffectsFormula",
                mainEffectsFormula)
            private$..interactionFactorX <- jmvcore::OptionString$new(
                "interactionFactorX",
                interactionFactorX)
            private$..interactionTraceFactor <- jmvcore::OptionString$new(
                "interactionTraceFactor",
                interactionTraceFactor)
            private$..interactionFactorY <- jmvcore::OptionString$new(
                "interactionFactorY",
                interactionFactorY)

            self$.addOption(private$..vars)
            self$.addOption(private$..mainEffectsFormula)
            self$.addOption(private$..interactionFactorX)
            self$.addOption(private$..interactionTraceFactor)
            self$.addOption(private$..interactionFactorY)
        }),
    active = list(
        vars = function() private$..vars$value,
        mainEffectsFormula = function() private$..mainEffectsFormula$value,
        interactionFactorX = function() private$..interactionFactorX$value,
        interactionTraceFactor = function() private$..interactionTraceFactor$value,
        interactionFactorY = function() private$..interactionFactorY$value),
    private = list(
        ..vars = NA,
        ..mainEffectsFormula = NA,
        ..interactionFactorX = NA,
        ..interactionTraceFactor = NA,
        ..interactionFactorY = NA)
)

mainEffectsInteractionResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mainEffectsInteractionResults",
    inherit = jmvcore::Group,
    active = list(
        usage = function() private$.items[["usage"]],
        mainEffectsPlot = function() private$.items[["mainEffectsPlot"]],
        interactionPlot = function() private$.items[["interactionPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Main Effects and Interaction Plots")
            self$add(jmvcore::Html$new(
                options=options,
                name="usage",
                title="Usage",
                visible=TRUE))
            self$add(jmvcore::Image$new(
                options=options,
                name="mainEffectsPlot",
                title="Main Effects Plot",
                width=450,
                height=350,
                renderFun=".mainEffectsPlot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="interactionPlot",
                title="Interaction Plot",
                width=450,
                height=350,
                renderFun=".interactionPlot"))}))

mainEffectsInteractionBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mainEffectsInteractionBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "DoE",
                name = "mainEffectsInteraction",
                version = c(1,0,0),
                options = options,
                results = mainEffectsInteractionResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Main Effects and Interaction Plots
#'
#' 
#' @param data .
#' @param vars .
#' @param mainEffectsFormula .
#' @param interactionFactorX .
#' @param interactionTraceFactor .
#' @param interactionFactorY .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$usage} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$mainEffectsPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$interactionPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
mainEffectsInteraction <- function(
    data,
    vars,
    mainEffectsFormula,
    interactionFactorX,
    interactionTraceFactor,
    interactionFactorY) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mainEffectsInteraction requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- mainEffectsInteractionOptions$new(
        vars = vars,
        mainEffectsFormula = mainEffectsFormula,
        interactionFactorX = interactionFactorX,
        interactionTraceFactor = interactionTraceFactor,
        interactionFactorY = interactionFactorY)

    analysis <- mainEffectsInteractionClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

