
# This file is automatically generated, you probably don't want to edit this

mixModelOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mixModelOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            indep = NULL,
            deps = NULL,
            mixModelType = "2",
            modelContourPlotSwitch = FALSE,
            effectPlotModelType = "2",
            numFactors = 2,
            direction = "1",
            numProcessVar = 0,
            effectPlotSwitch = FALSE,
            mixturePlotModelType = "2",
            numBreaks = 10,
            mixtureContourPlotSwitch = FALSE, ...) {

            super$initialize(
                package="DoE",
                name="mixModel",
                requiresData=TRUE,
                ...)

            private$..indep <- jmvcore::OptionVariable$new(
                "indep",
                indep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..deps <- jmvcore::OptionVariables$new(
                "deps",
                deps)
            private$..mixModelType <- jmvcore::OptionList$new(
                "mixModelType",
                mixModelType,
                options=list(
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6"),
                default="2")
            private$..modelContourPlotSwitch <- jmvcore::OptionBool$new(
                "modelContourPlotSwitch",
                modelContourPlotSwitch,
                default=FALSE)
            private$..effectPlotModelType <- jmvcore::OptionList$new(
                "effectPlotModelType",
                effectPlotModelType,
                options=list(
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6"),
                default="2")
            private$..numFactors <- jmvcore::OptionInteger$new(
                "numFactors",
                numFactors,
                default=2)
            private$..direction <- jmvcore::OptionList$new(
                "direction",
                direction,
                options=list(
                    "1",
                    "2"),
                default="1")
            private$..numProcessVar <- jmvcore::OptionInteger$new(
                "numProcessVar",
                numProcessVar,
                default=0)
            private$..effectPlotSwitch <- jmvcore::OptionBool$new(
                "effectPlotSwitch",
                effectPlotSwitch,
                default=FALSE)
            private$..mixturePlotModelType <- jmvcore::OptionList$new(
                "mixturePlotModelType",
                mixturePlotModelType,
                options=list(
                    "1",
                    "2",
                    "4"),
                default="2")
            private$..numBreaks <- jmvcore::OptionInteger$new(
                "numBreaks",
                numBreaks,
                default=10)
            private$..mixtureContourPlotSwitch <- jmvcore::OptionBool$new(
                "mixtureContourPlotSwitch",
                mixtureContourPlotSwitch,
                default=FALSE)

            self$.addOption(private$..indep)
            self$.addOption(private$..deps)
            self$.addOption(private$..mixModelType)
            self$.addOption(private$..modelContourPlotSwitch)
            self$.addOption(private$..effectPlotModelType)
            self$.addOption(private$..numFactors)
            self$.addOption(private$..direction)
            self$.addOption(private$..numProcessVar)
            self$.addOption(private$..effectPlotSwitch)
            self$.addOption(private$..mixturePlotModelType)
            self$.addOption(private$..numBreaks)
            self$.addOption(private$..mixtureContourPlotSwitch)
        }),
    active = list(
        indep = function() private$..indep$value,
        deps = function() private$..deps$value,
        mixModelType = function() private$..mixModelType$value,
        modelContourPlotSwitch = function() private$..modelContourPlotSwitch$value,
        effectPlotModelType = function() private$..effectPlotModelType$value,
        numFactors = function() private$..numFactors$value,
        direction = function() private$..direction$value,
        numProcessVar = function() private$..numProcessVar$value,
        effectPlotSwitch = function() private$..effectPlotSwitch$value,
        mixturePlotModelType = function() private$..mixturePlotModelType$value,
        numBreaks = function() private$..numBreaks$value,
        mixtureContourPlotSwitch = function() private$..mixtureContourPlotSwitch$value),
    private = list(
        ..indep = NA,
        ..deps = NA,
        ..mixModelType = NA,
        ..modelContourPlotSwitch = NA,
        ..effectPlotModelType = NA,
        ..numFactors = NA,
        ..direction = NA,
        ..numProcessVar = NA,
        ..effectPlotSwitch = NA,
        ..mixturePlotModelType = NA,
        ..numBreaks = NA,
        ..mixtureContourPlotSwitch = NA)
)

mixModelResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mixModelResults",
    inherit = jmvcore::Group,
    active = list(
        usage = function() private$.items[["usage"]],
        mixModel = function() private$.items[["mixModel"]],
        modelContourPlot = function() private$.items[["modelContourPlot"]],
        effectPlot = function() private$.items[["effectPlot"]],
        mixtureContourPlot = function() private$.items[["mixtureContourPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Mixture Model")
            self$add(jmvcore::Html$new(
                options=options,
                name="usage",
                title="Usage",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="mixModel",
                title="Mixture Model"))
            self$add(jmvcore::Image$new(
                options=options,
                name="modelContourPlot",
                title="Model Contour Plot",
                width=350,
                height=350,
                renderFun=".modelContourPlot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="effectPlot",
                title="Effect Plot",
                width=350,
                height=350,
                renderFun=".effectPlot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="mixtureContourPlot",
                title="Mixture Contour Plot",
                width=350,
                height=350,
                renderFun=".mixtureContourPlot"))}))

mixModelBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mixModelBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "DoE",
                name = "mixModel",
                version = c(1,0,0),
                options = options,
                results = mixModelResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Mixture Model
#'
#' 
#' @param data .
#' @param indep .
#' @param deps .
#' @param mixModelType .
#' @param modelContourPlotSwitch .
#' @param effectPlotModelType .
#' @param numFactors .
#' @param direction .
#' @param numProcessVar .
#' @param effectPlotSwitch .
#' @param mixturePlotModelType .
#' @param numBreaks .
#' @param mixtureContourPlotSwitch .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$usage} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$mixModel} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$modelContourPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$effectPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$mixtureContourPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
mixModel <- function(
    data,
    indep,
    deps,
    mixModelType = "2",
    modelContourPlotSwitch = FALSE,
    effectPlotModelType = "2",
    numFactors = 2,
    direction = "1",
    numProcessVar = 0,
    effectPlotSwitch = FALSE,
    mixturePlotModelType = "2",
    numBreaks = 10,
    mixtureContourPlotSwitch = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mixModel requires jmvcore to be installed (restart may be required)")

    if ( ! missing(indep)) indep <- jmvcore::resolveQuo(jmvcore::enquo(indep))
    if ( ! missing(deps)) deps <- jmvcore::resolveQuo(jmvcore::enquo(deps))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(indep), indep, NULL),
            `if`( ! missing(deps), deps, NULL))


    options <- mixModelOptions$new(
        indep = indep,
        deps = deps,
        mixModelType = mixModelType,
        modelContourPlotSwitch = modelContourPlotSwitch,
        effectPlotModelType = effectPlotModelType,
        numFactors = numFactors,
        direction = direction,
        numProcessVar = numProcessVar,
        effectPlotSwitch = effectPlotSwitch,
        mixturePlotModelType = mixturePlotModelType,
        numBreaks = numBreaks,
        mixtureContourPlotSwitch = mixtureContourPlotSwitch)

    analysis <- mixModelClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

