
# This file is automatically generated, you probably don't want to edit this

mixModelOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mixModelOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            indeps = NULL,
            mixModelType = "2",
            mixturePlotModelType = "2",
            numBreaks = 10,
            mixtureContourPlotSwitch = FALSE,
            effectPlotModelType = "2",
            numFactors = 2,
            direction = "1",
            numProcessVar = 0,
            effectPlotSwitch = FALSE,
            modelContourPlotSwitch = FALSE, ...) {

            super$initialize(
                package="DoE",
                name="mixModel",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..indeps <- jmvcore::OptionVariables$new(
                "indeps",
                indeps)
            private$..mixModelType <- jmvcore::OptionList$new(
                "mixModelType",
                mixModelType,
                options=list(
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6"),
                default="2")
            private$..mixturePlotModelType <- jmvcore::OptionList$new(
                "mixturePlotModelType",
                mixturePlotModelType,
                options=list(
                    "1",
                    "2",
                    "4"),
                default="2")
            private$..numBreaks <- jmvcore::OptionInteger$new(
                "numBreaks",
                numBreaks,
                default=10)
            private$..mixtureContourPlotSwitch <- jmvcore::OptionBool$new(
                "mixtureContourPlotSwitch",
                mixtureContourPlotSwitch,
                default=FALSE)
            private$..effectPlotModelType <- jmvcore::OptionList$new(
                "effectPlotModelType",
                effectPlotModelType,
                options=list(
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6"),
                default="2")
            private$..numFactors <- jmvcore::OptionInteger$new(
                "numFactors",
                numFactors,
                default=2)
            private$..direction <- jmvcore::OptionList$new(
                "direction",
                direction,
                options=list(
                    "1",
                    "2"),
                default="1")
            private$..numProcessVar <- jmvcore::OptionInteger$new(
                "numProcessVar",
                numProcessVar,
                default=0)
            private$..effectPlotSwitch <- jmvcore::OptionBool$new(
                "effectPlotSwitch",
                effectPlotSwitch,
                default=FALSE)
            private$..modelContourPlotSwitch <- jmvcore::OptionBool$new(
                "modelContourPlotSwitch",
                modelContourPlotSwitch,
                default=FALSE)

            self$.addOption(private$..dep)
            self$.addOption(private$..indeps)
            self$.addOption(private$..mixModelType)
            self$.addOption(private$..mixturePlotModelType)
            self$.addOption(private$..numBreaks)
            self$.addOption(private$..mixtureContourPlotSwitch)
            self$.addOption(private$..effectPlotModelType)
            self$.addOption(private$..numFactors)
            self$.addOption(private$..direction)
            self$.addOption(private$..numProcessVar)
            self$.addOption(private$..effectPlotSwitch)
            self$.addOption(private$..modelContourPlotSwitch)
        }),
    active = list(
        dep = function() private$..dep$value,
        indeps = function() private$..indeps$value,
        mixModelType = function() private$..mixModelType$value,
        mixturePlotModelType = function() private$..mixturePlotModelType$value,
        numBreaks = function() private$..numBreaks$value,
        mixtureContourPlotSwitch = function() private$..mixtureContourPlotSwitch$value,
        effectPlotModelType = function() private$..effectPlotModelType$value,
        numFactors = function() private$..numFactors$value,
        direction = function() private$..direction$value,
        numProcessVar = function() private$..numProcessVar$value,
        effectPlotSwitch = function() private$..effectPlotSwitch$value,
        modelContourPlotSwitch = function() private$..modelContourPlotSwitch$value),
    private = list(
        ..dep = NA,
        ..indeps = NA,
        ..mixModelType = NA,
        ..mixturePlotModelType = NA,
        ..numBreaks = NA,
        ..mixtureContourPlotSwitch = NA,
        ..effectPlotModelType = NA,
        ..numFactors = NA,
        ..direction = NA,
        ..numProcessVar = NA,
        ..effectPlotSwitch = NA,
        ..modelContourPlotSwitch = NA)
)

mixModelResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mixModelResults",
    inherit = jmvcore::Group,
    active = list(
        usage = function() private$.items[["usage"]],
        mixModel = function() private$.items[["mixModel"]],
        mixtureContourPlot = function() private$.items[["mixtureContourPlot"]],
        effectPlot = function() private$.items[["effectPlot"]],
        modelContourPlot = function() private$.items[["modelContourPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Mixture Model")
            self$add(jmvcore::Html$new(
                options=options,
                name="usage",
                title="Usage",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="mixModel",
                title="Mixture Model"))
            self$add(jmvcore::Image$new(
                options=options,
                name="mixtureContourPlot",
                title="Mixture Contour Plot",
                width=350,
                height=350,
                renderFun=".mixtureContourPlot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="effectPlot",
                title="Mixture Effect Plot",
                width=350,
                height=350,
                renderFun=".effectPlot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="modelContourPlot",
                title="Model Contour Plot",
                width=350,
                height=350,
                renderFun=".modelContourPlot"))}))

mixModelBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mixModelBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "DoE",
                name = "mixModel",
                version = c(1,0,0),
                options = options,
                results = mixModelResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Mixture Model
#'
#' 
#' @param data .
#' @param dep .
#' @param indeps .
#' @param mixModelType .
#' @param mixturePlotModelType .
#' @param numBreaks .
#' @param mixtureContourPlotSwitch .
#' @param effectPlotModelType .
#' @param numFactors .
#' @param direction .
#' @param numProcessVar .
#' @param effectPlotSwitch .
#' @param modelContourPlotSwitch .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$usage} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$mixModel} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$mixtureContourPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$effectPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$modelContourPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
mixModel <- function(
    data,
    dep,
    indeps,
    mixModelType = "2",
    mixturePlotModelType = "2",
    numBreaks = 10,
    mixtureContourPlotSwitch = FALSE,
    effectPlotModelType = "2",
    numFactors = 2,
    direction = "1",
    numProcessVar = 0,
    effectPlotSwitch = FALSE,
    modelContourPlotSwitch = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mixModel requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(indeps)) indeps <- jmvcore::resolveQuo(jmvcore::enquo(indeps))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(indeps), indeps, NULL))


    options <- mixModelOptions$new(
        dep = dep,
        indeps = indeps,
        mixModelType = mixModelType,
        mixturePlotModelType = mixturePlotModelType,
        numBreaks = numBreaks,
        mixtureContourPlotSwitch = mixtureContourPlotSwitch,
        effectPlotModelType = effectPlotModelType,
        numFactors = numFactors,
        direction = direction,
        numProcessVar = numProcessVar,
        effectPlotSwitch = effectPlotSwitch,
        modelContourPlotSwitch = modelContourPlotSwitch)

    analysis <- mixModelClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

