
# This file is automatically generated, you probably don't want to edit this

normalQQOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "normalQQOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            norVar = NULL, ...) {

            super$initialize(
                package="DoE",
                name="normalQQ",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars)
            private$..norVar <- jmvcore::OptionString$new(
                "norVar",
                norVar)

            self$.addOption(private$..vars)
            self$.addOption(private$..norVar)
        }),
    active = list(
        vars = function() private$..vars$value,
        norVar = function() private$..norVar$value),
    private = list(
        ..vars = NA,
        ..norVar = NA)
)

normalQQResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "normalQQResults",
    inherit = jmvcore::Group,
    active = list(
        usage = function() private$.items[["usage"]],
        normalQQPlot = function() private$.items[["normalQQPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Normal QQ Plot")
            self$add(jmvcore::Html$new(
                options=options,
                name="usage",
                title="Usage",
                visible=TRUE))
            self$add(jmvcore::Image$new(
                options=options,
                name="normalQQPlot",
                title="Normal QQ Plot",
                width=450,
                height=350,
                renderFun=".normalQQPlot"))}))

normalQQBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "normalQQBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "DoE",
                name = "normalQQ",
                version = c(1,0,0),
                options = options,
                results = normalQQResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Normal QQ Plot
#'
#' 
#' @param data .
#' @param vars .
#' @param norVar .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$usage} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$normalQQPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
normalQQ <- function(
    data,
    vars,
    norVar) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("normalQQ requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- normalQQOptions$new(
        vars = vars,
        norVar = norVar)

    analysis <- normalQQClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

