
# This file is automatically generated, you probably don't want to edit this

resMeansOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "resMeansOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            deps = NULL,
            indeps = NULL,
            resVars = NULL,
            indepPlot = NULL, ...) {

            super$initialize(
                package="DoE",
                name="resMeans",
                requiresData=TRUE,
                ...)

            private$..deps <- jmvcore::OptionVariables$new(
                "deps",
                deps,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..indeps <- jmvcore::OptionVariables$new(
                "indeps",
                indeps)
            private$..resVars <- jmvcore::OptionString$new(
                "resVars",
                resVars)
            private$..indepPlot <- jmvcore::OptionString$new(
                "indepPlot",
                indepPlot)

            self$.addOption(private$..deps)
            self$.addOption(private$..indeps)
            self$.addOption(private$..resVars)
            self$.addOption(private$..indepPlot)
        }),
    active = list(
        deps = function() private$..deps$value,
        indeps = function() private$..indeps$value,
        resVars = function() private$..resVars$value,
        indepPlot = function() private$..indepPlot$value),
    private = list(
        ..deps = NA,
        ..indeps = NA,
        ..resVars = NA,
        ..indepPlot = NA)
)

resMeansResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "resMeansResults",
    inherit = jmvcore::Group,
    active = list(
        usage = function() private$.items[["usage"]],
        resTableMeans = function() private$.items[["resTableMeans"]],
        mainEffectsPlotMeans = function() private$.items[["mainEffectsPlotMeans"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Response Means")
            self$add(jmvcore::Html$new(
                options=options,
                name="usage",
                title="Usage",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="resTableMeans",
                title="Response Table for Means"))
            self$add(jmvcore::Image$new(
                options=options,
                name="mainEffectsPlotMeans",
                title="Main Effects Plot for Means",
                width=450,
                height=350,
                renderFun=".mainEffectsPlotMeans"))}))

resMeansBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "resMeansBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "DoE",
                name = "resMeans",
                version = c(1,0,0),
                options = options,
                results = resMeansResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Response Means
#'
#' 
#' @param data .
#' @param deps .
#' @param indeps .
#' @param resVars .
#' @param indepPlot .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$usage} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$resTableMeans} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$mainEffectsPlotMeans} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
resMeans <- function(
    data,
    deps,
    indeps,
    resVars,
    indepPlot) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("resMeans requires jmvcore to be installed (restart may be required)")

    if ( ! missing(deps)) deps <- jmvcore::resolveQuo(jmvcore::enquo(deps))
    if ( ! missing(indeps)) indeps <- jmvcore::resolveQuo(jmvcore::enquo(indeps))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(deps), deps, NULL),
            `if`( ! missing(indeps), indeps, NULL))


    options <- resMeansOptions$new(
        deps = deps,
        indeps = indeps,
        resVars = resVars,
        indepPlot = indepPlot)

    analysis <- resMeansClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

