
# This file is automatically generated, you probably don't want to edit this

resOptimizationOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "resOptimizationOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            deps = NULL,
            indeps = NULL,
            modelTerms = NULL,
            numFactors = NULL,
            actualValues = NULL,
            targetGoals = NULL,
            lowerUpperBounds = NULL, ...) {

            super$initialize(
                package="DoE",
                name="resOptimization",
                requiresData=TRUE,
                ...)

            private$..deps <- jmvcore::OptionVariables$new(
                "deps",
                deps,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..indeps <- jmvcore::OptionVariables$new(
                "indeps",
                indeps)
            private$..modelTerms <- jmvcore::OptionTerms$new(
                "modelTerms",
                modelTerms)
            private$..numFactors <- jmvcore::OptionString$new(
                "numFactors",
                numFactors)
            private$..actualValues <- jmvcore::OptionString$new(
                "actualValues",
                actualValues)
            private$..targetGoals <- jmvcore::OptionString$new(
                "targetGoals",
                targetGoals)
            private$..lowerUpperBounds <- jmvcore::OptionString$new(
                "lowerUpperBounds",
                lowerUpperBounds)

            self$.addOption(private$..deps)
            self$.addOption(private$..indeps)
            self$.addOption(private$..modelTerms)
            self$.addOption(private$..numFactors)
            self$.addOption(private$..actualValues)
            self$.addOption(private$..targetGoals)
            self$.addOption(private$..lowerUpperBounds)
        }),
    active = list(
        deps = function() private$..deps$value,
        indeps = function() private$..indeps$value,
        modelTerms = function() private$..modelTerms$value,
        numFactors = function() private$..numFactors$value,
        actualValues = function() private$..actualValues$value,
        targetGoals = function() private$..targetGoals$value,
        lowerUpperBounds = function() private$..lowerUpperBounds$value),
    private = list(
        ..deps = NA,
        ..indeps = NA,
        ..modelTerms = NA,
        ..numFactors = NA,
        ..actualValues = NA,
        ..targetGoals = NA,
        ..lowerUpperBounds = NA)
)

resOptimizationResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "resOptimizationResults",
    inherit = jmvcore::Group,
    active = list(
        usage = function() private$.items[["usage"]],
        globalSolution = function() private$.items[["globalSolution"]],
        predResponses = function() private$.items[["predResponses"]],
        individualDes = function() private$.items[["individualDes"]],
        compositeDes = function() private$.items[["compositeDes"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Response Optimization")
            self$add(jmvcore::Html$new(
                options=options,
                name="usage",
                title="Usage",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="globalSolution",
                title="Global Solution"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="predResponses",
                title="Predicted Responses"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="individualDes",
                title="Individual Desirability"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="compositeDes",
                title="Composite (Overall) Desirability"))}))

resOptimizationBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "resOptimizationBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "DoE",
                name = "resOptimization",
                version = c(1,0,0),
                options = options,
                results = resOptimizationResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Response Optimization
#'
#' 
#' @param data .
#' @param deps .
#' @param indeps .
#' @param modelTerms .
#' @param numFactors .
#' @param actualValues .
#' @param targetGoals .
#' @param lowerUpperBounds .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$usage} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$globalSolution} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$predResponses} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$individualDes} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$compositeDes} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
resOptimization <- function(
    data,
    deps,
    indeps,
    modelTerms,
    numFactors,
    actualValues,
    targetGoals,
    lowerUpperBounds) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("resOptimization requires jmvcore to be installed (restart may be required)")

    if ( ! missing(deps)) deps <- jmvcore::resolveQuo(jmvcore::enquo(deps))
    if ( ! missing(indeps)) indeps <- jmvcore::resolveQuo(jmvcore::enquo(indeps))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(deps), deps, NULL),
            `if`( ! missing(indeps), indeps, NULL))

    if (inherits(modelTerms, "formula")) modelTerms <- jmvcore::decomposeFormula(modelTerms)

    options <- resOptimizationOptions$new(
        deps = deps,
        indeps = indeps,
        modelTerms = modelTerms,
        numFactors = numFactors,
        actualValues = actualValues,
        targetGoals = targetGoals,
        lowerUpperBounds = lowerUpperBounds)

    analysis <- resOptimizationClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

