
# This file is automatically generated, you probably don't want to edit this

simplexCentroidOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "simplexCentroidOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            fac = NULL,
            designPoints = FALSE, ...) {

            super$initialize(
                package="DoE",
                name="simplexCentroid",
                requiresData=TRUE,
                ...)

            private$..fac <- jmvcore::OptionNumber$new(
                "fac",
                fac)
            private$..designPoints <- jmvcore::OptionBool$new(
                "designPoints",
                designPoints,
                default=FALSE)

            self$.addOption(private$..fac)
            self$.addOption(private$..designPoints)
        }),
    active = list(
        fac = function() private$..fac$value,
        designPoints = function() private$..designPoints$value),
    private = list(
        ..fac = NA,
        ..designPoints = NA)
)

simplexCentroidResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "simplexCentroidResults",
    inherit = jmvcore::Group,
    active = list(
        usage = function() private$.items[["usage"]],
        text = function() private$.items[["text"]],
        designPointsPlot = function() private$.items[["designPointsPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Simplex Centroid")
            self$add(jmvcore::Html$new(
                options=options,
                name="usage",
                title="Usage",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Simplex Centroid"))
            self$add(jmvcore::Image$new(
                options=options,
                name="designPointsPlot",
                title="Design Points Plot",
                width=350,
                height=350,
                renderFun=".designPointsPlot"))}))

simplexCentroidBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "simplexCentroidBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "DoE",
                name = "simplexCentroid",
                version = c(1,0,0),
                options = options,
                results = simplexCentroidResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Simplex Centroid
#'
#' 
#' @param data .
#' @param fac .
#' @param designPoints .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$usage} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$designPointsPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
simplexCentroid <- function(
    data,
    fac,
    designPoints = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("simplexCentroid requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- simplexCentroidOptions$new(
        fac = fac,
        designPoints = designPoints)

    analysis <- simplexCentroidClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

