
# This file is automatically generated, you probably don't want to edit this

taguchiOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "taguchiOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            numberFactors = NULL,
            nameFactors = NULL,
            numberFactorLevels = NULL,
            eachColumnIndex = NULL,
            eachFactorLevels = NULL,
            design = NULL,
            replicates = 1,
            randomize = NULL, ...) {

            super$initialize(
                package="DoE",
                name="taguchi",
                requiresData=TRUE,
                ...)

            private$..numberFactors <- jmvcore::OptionInteger$new(
                "numberFactors",
                numberFactors)
            private$..nameFactors <- jmvcore::OptionString$new(
                "nameFactors",
                nameFactors)
            private$..numberFactorLevels <- jmvcore::OptionInteger$new(
                "numberFactorLevels",
                numberFactorLevels)
            private$..eachColumnIndex <- jmvcore::OptionString$new(
                "eachColumnIndex",
                eachColumnIndex)
            private$..eachFactorLevels <- jmvcore::OptionString$new(
                "eachFactorLevels",
                eachFactorLevels)
            private$..design <- jmvcore::OptionList$new(
                "design",
                design,
                options=list(
                    "L4_2",
                    "L8_2",
                    "L9_3",
                    "L12_2",
                    "L16_2",
                    "L16_4",
                    "L18_2_3",
                    "L25_5",
                    "L27_3",
                    "L32_2",
                    "L32_2_4",
                    "L36_2_3_a",
                    "L36_2_3_b",
                    "L50_2_5",
                    "L8_4_2",
                    "L16_4_2_a",
                    "L16_4_2_b",
                    "L16_4_2_c",
                    "L16_4_2_d",
                    "L18_6_3"))
            private$..replicates <- jmvcore::OptionInteger$new(
                "replicates",
                replicates,
                default=1)
            private$..randomize <- jmvcore::OptionBool$new(
                "randomize",
                randomize)

            self$.addOption(private$..numberFactors)
            self$.addOption(private$..nameFactors)
            self$.addOption(private$..numberFactorLevels)
            self$.addOption(private$..eachColumnIndex)
            self$.addOption(private$..eachFactorLevels)
            self$.addOption(private$..design)
            self$.addOption(private$..replicates)
            self$.addOption(private$..randomize)
        }),
    active = list(
        numberFactors = function() private$..numberFactors$value,
        nameFactors = function() private$..nameFactors$value,
        numberFactorLevels = function() private$..numberFactorLevels$value,
        eachColumnIndex = function() private$..eachColumnIndex$value,
        eachFactorLevels = function() private$..eachFactorLevels$value,
        design = function() private$..design$value,
        replicates = function() private$..replicates$value,
        randomize = function() private$..randomize$value),
    private = list(
        ..numberFactors = NA,
        ..nameFactors = NA,
        ..numberFactorLevels = NA,
        ..eachColumnIndex = NA,
        ..eachFactorLevels = NA,
        ..design = NA,
        ..replicates = NA,
        ..randomize = NA)
)

taguchiResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "taguchiResults",
    inherit = jmvcore::Group,
    active = list(
        usage = function() private$.items[["usage"]],
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Taguchi")
            self$add(jmvcore::Html$new(
                options=options,
                name="usage",
                title="Usage",
                visible=TRUE))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Taguchi"))}))

taguchiBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "taguchiBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "DoE",
                name = "taguchi",
                version = c(1,0,0),
                options = options,
                results = taguchiResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Taguchi
#'
#' 
#' @param data .
#' @param numberFactors .
#' @param nameFactors .
#' @param numberFactorLevels .
#' @param eachColumnIndex .
#' @param eachFactorLevels .
#' @param design .
#' @param replicates .
#' @param randomize .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$usage} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
taguchi <- function(
    data,
    numberFactors,
    nameFactors,
    numberFactorLevels,
    eachColumnIndex,
    eachFactorLevels,
    design,
    replicates = 1,
    randomize) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("taguchi requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- taguchiOptions$new(
        numberFactors = numberFactors,
        nameFactors = nameFactors,
        numberFactorLevels = numberFactorLevels,
        eachColumnIndex = eachColumnIndex,
        eachFactorLevels = eachFactorLevels,
        design = design,
        replicates = replicates,
        randomize = randomize)

    analysis <- taguchiClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

